# Generated by Django 3.2.4 on 2021-06-28 19:22

from django.db import migrations, models
import escrow.user_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('firts_name', models.CharField(blank=True, max_length=400)),
                ('other_names', models.CharField(blank=True, max_length=400)),
                ('contact', models.CharField(blank=True, max_length=400)),
                ('gender', models.CharField(blank=True, max_length=400)),
                ('location', models.CharField(blank=True, max_length=400)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('vendor_status', models.BooleanField(default=False)),
                ('Customer_status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', escrow.user_manager.UserManager()),
            ],
        ),
    ]
